export const ErrorCodes = {
    // AUTH / LOGIN
    ERR_MISSING_IDENTIFIER: "ERR_MISSING_IDENTIFIER",
    ERR_MISSING_PASSWORD: "ERR_MISSING_PASSWORD",
    ERR_USER_NOT_FOUND: "ERR_USER_NOT_FOUND",
    ERR_INVALID_PASSWORD: "ERR_INVALID_PASSWORD",
    ERR_TOO_MANY_ATTEMPTS: "ERR_TOO_MANY_ATTEMPTS",
  
    // EMAIL / OTP
    ERR_MISSING_EMAIL: "ERR_MISSING_EMAIL",
    ERR_ALREADY_VERIFIED: "ERR_ALREADY_VERIFIED",
    ERR_MISSING_OTP: "ERR_MISSING_OTP",
    ERR_INVALID_OTP: "ERR_INVALID_OTP",
    ERR_EXPIRED_OTP: "ERR_EXPIRED_OTP",
    ERR_COOLDOWN_ACTIVE: "ERR_COOLDOWN_ACTIVE",
    ERR_OTP_LIMIT_REACHED: "ERR_OTP_LIMIT_REACHED",
  
    // TOKEN
    ERR_TOKEN_MISSING: "ERR_TOKEN_MISSING",
    ERR_TOKEN_INVALID: "ERR_TOKEN_INVALID",
    ERR_TOKEN_EXPIRED: "ERR_TOKEN_EXPIRED",
  
    // SERVER
    ERR_SERVER: "ERR_SERVER",
  };
  